# Generated by Django 3.2.9 on 2021-11-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Department_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Department name',
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=70)),
                ('date_of_birth', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department_app.department')),
            ],
            options={
                'verbose_name': 'Employee name',
                'db_table': 'employees',
            },
        ),
    ]
