# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pylint-django
          pip install -r requirements.txt
          
    - name: pylint check
      run: |
          pylint --load-plugins=pylint_django --django-settings-module=depatment_project.settings depatment_project/*
        
    - name: Install Coveralls       
      run: |
        pip install coveralls
        coverage run --source=depatment_project depatment_project/manage.py test department_app  
   
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
